# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

dotenv: ['.env']

vars:
  GREETING: Hello, world!

tasks:
  default:
    desc: Print a greeting message
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  server:
    desc: Run the web server
    cmds:
      - cd server && npm run dev
    silent: true
  # docker:
  #   desc: run docker compose 
  #   cmds:
  #     - docker compose -f docker-compose.yaml up -d
  #   silent: true
  docker:db:run:
    desc: Run the docker compose for database
    cmds:
      - docker compose -f ./docker/postgres-docker-compose.yaml up --build -d
    silent: true
  docker:db:delete:
    desc: Delete the docker compose for database
    cmds:
      - docker compose -f ./docker/postgres-docker-compose.yaml down -v
    silent: true
