# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

dotenv: ['.env']

vars:
  GREETING: Hello, world!

tasks:
  default:
    desc: Print a greeting message
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  server:
    desc: Run the web server
    cmds:
      - cd server && npm run dev
    silent: true
